name: Feature Request
description: File a feature request
title: "🆕: "
labels: ["enhancement"]
assignees:
  - renfordt
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: what-happened
    attributes:
      label: What feature would you like to have?
      description: Also tell us, what the benefits are?
      placeholder: A new feature please.
      value: "A new feature please."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/renfordt/larvatar/blob/main/contributing.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true